### ISSUE TITLE
Create a CommandBox Scripts Panel like NPM Scripts

### ISSUE THREAD

**Issue by lmajano** [KamasamaK/vscode-cfml#46] opened 2020-01-23 21:33 UTC
![Screen Shot 2020-01-23 at 3 31 53 PM](https://user-images.githubusercontent.com/137111/73025665-98ea5f80-3df5-11ea-83dc-e6c8a619f6ea.png)

Is there a way to create a CommandBox or Box Scripts panel in VS Code so we can navigate the box.json `scripts` and be able to execute them directly from vscode.

**Comment by KamasamaK** [comment] 2020-01-30 17:48
I think this is a duplicate of #42. I did start on this, but unfortunately I haven't had much time to dedicate to that project.

**Comment by lmajano** [comment] 2020-01-30 18:14
@KamasamaK how can we help? Is there a way you can give us a code demo of how to work on the extension and some of my guys can help on this?

**Closed** 2020-02-23 01:38 UTC
